#!/bin/bash
# SMS via Email to SMS Gateway


EMAIL="$HOME/bin/mail"
HOSTSUBJECT="$NOTIFY_NOTIFICATIONTYPE $NOTIFY_HOSTALIAS"
SERVICESUBJECT="$NOTIFY_NOTIFICATIONTYPE $NOTIFY_HOSTALIAS $NOTIFY_SERVICEDESC"

# For Service notification
if [ "$NOTIFY_WHAT" = "SERVICE" ]; then
	if [[ -z $NOTIFY_NOTIFICATIONCOMMENT ]]
	then
		echo "$NOTIFY_SERVICEOUTPUT" | $EMAIL -s "$SERVICESUBJECT" $NOTIFY_PARAMETER_1
	else
		echo "<$NOTIFY_NOTIFICATIONCOMMENT> (by $NOTIFY_NOTIFICATIONAUTHORNAME) $NOTIFY_SERVICEOUTPUT" | $EMAIL -s "$SERVICESUBJECT" $NOTIFY_PARAMETER_1
	fi

# For Host notification
else
	if [[ -z $NOTIFY_NOTIFICATIONCOMMENT ]]
	then
		echo "$NOTIFY_HOSTOUTPUT" | $EMAIL -s "$HOSTSUBJECT" $NOTIFY_PARAMETER_1
	else
		echo "<$NOTIFY_NOTIFICATIONCOMMENT> (by $NOTIFY_NOTIFICATIONAUTHORNAME) $NOTIFY_HOSTOUTPUT" | $EMAIL -s "$HOSTSUBJECT" $NOTIFY_PARAMETER_1
	fi
fi
