#!/bin/bash
# Automated On-call Rotation Notification


EMAIL="$HOME/bin/mail"
HOSTSUBJECT="$NOTIFY_NOTIFICATIONTYPE $NOTIFY_HOSTALIAS"
SERVICESUBJECT="$NOTIFY_NOTIFICATIONTYPE $NOTIFY_HOSTALIAS $NOTIFY_SERVICEDESC"

FLAG=0
PRIMARY="someone@somedomain.com"
SECONDARY="someone2@somedomain.com"

# Decide whether message should go to primary or secondary
if [[ ${NOTIFY_PARAMETER_1} = "primary" ]]; then
	TARGET=${PRIMARY}
elif [[ ${NOTIFY_PARAMETER_1} = "secondary" ]]; then
	TARGET=${SECONDARY}
else
	TARGET=${PRIMARY}
fi

# For Service notification
if [ "$NOTIFY_WHAT" = "SERVICE" ]; then
	if [[ -z $NOTIFY_NOTIFICATIONCOMMENT ]]
	then
		echo "$NOTIFY_SERVICEOUTPUT" | $EMAIL -s "$SERVICESUBJECT" $TARGET
	else
		echo "<$NOTIFY_NOTIFICATIONCOMMENT> (by $NOTIFY_NOTIFICATIONAUTHORNAME) $NOTIFY_SERVICEOUTPUT" | $EMAIL -s "$SERVICESUBJECT" $TARGET
	fi

# For Host notification
else
	if [[ -z $NOTIFY_NOTIFICATIONCOMMENT ]]
	then
		echo "$NOTIFY_HOSTOUTPUT" | $EMAIL -s "$HOSTSUBJECT" $TARGET
	else
		echo "<$NOTIFY_NOTIFICATIONCOMMENT> (by $NOTIFY_NOTIFICATIONAUTHORNAME) $NOTIFY_HOSTOUTPUT" | $EMAIL -s "$HOSTSUBJECT" $TARGET
	fi
fi
