#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# based upon 'qemu' from
# 12/2010 Matthias Henze
#
# updated for libvirtd (virsh) by
# Jonathan Mills 09/2011
#
# removed performance data, and only record assigned CPU & RAM to speed things up by
# Henry Huang 04/2014
#


# Example output from agent:
# <<<qemu>>>
# 4 i-4B9008BE running 2 2048
# 5 i-44F608B6 running 1 2048




# inventory
def inventory_qemu(checkname, info):
    inventory = []
    for line in info:
        if line[2] == "running":  # only VM's running while inventory are monitored !
            vm = line[1] # we want to capture hostname, not vm id here

	    # Fix annoying OpenStack misnaming of VMs
	    name = vm.split('-')
	    if name[0] == "instance":
		name[0] = "i"
	    vm = '-'.join(name)
	    ##

            inventory.append( (vm, None) )
    return inventory

# check
def check_qemu(name, param, info):
    for line in info:

	vm = line[1]
	host = vm.split('-')
	if host[0] == "instance":
	    host[0] = "i"
	vm = '-'.join(host)

        if vm == name:
            item = line[0]
            status = line[2]
            cpu = line[3]
            ram = line[4]
            infotext = "%s  (id: %s, cpu: %s, ram: %s MB)" % (status, item, cpu, ram)
            if status == "running":
                return (0, "OK - status is " + infotext)
            else:
                return (2, "CRITICAL - status is " + infotext)
    #return (3, "UNKNOWN - VM %s not found in agent output" % item)
    return (3, "UNKNOWN - VM not found in agent output")

# declare the check to Check_MK
check_info['qemu'] = \
        (check_qemu, "VM %s", 1, inventory_qemu)
